export default {
    products: [
        {
            _id: '1',
            name: 'Cool Monitor',
            category: 'Computer Monitors',
            image:'./images/monitor-copy.png',
            brand: 'Samsung',
            price: 100,
            rating: 2.5,
            numReviews: 20,
            countInStock: 6, 
        },
        {
            _id: '2',
            name: 'Sweet Monitor',
            category: 'Computer Monitors',
            image:'./images/product-1.jpg',
            brand: 'Generic',
            price: 75,
            rating: 2,
            numReviews: 10,
            countInStock: 6, 
        },
        {
            _id: '3',
            name: 'Awesome PC Case',
            category: 'Gaming PC Tower Case',
            image:'./images/product-2.png',
            brand: 'Rainbow',
            price: 75,
            rating: 4.5,
            numReviews: 50,
            countInStock: 6, 
        },
        {
            _id: '4',
            name: 'Skytech Dark Angel',
            category: 'Computer Monitors',
            image:'./images/SkyTech-DarkAngel.jpg',
            brand: 'SkyTech',
            price: 1300,
            rating: 5,
            numReviews: 32,
            countInStock: 6, 
        },
        {
            _id: '5',
            name: 'Gaming Setup',
            category: 'Gaming Computer Setup',
            image:'./images/product-3.jpg',
            brand: 'Asus',
            price: 1000,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6, 
        },
        {
            _id: '6',
            name: 'Skytech Archangel',
            category: 'Gaming PC',
            image:'./images/product-4.jpg',
            brand: 'Skytech',
            price: 1200,
            rating: 5,
            numReviews: 25,
            countInStock: 6, 
        },

    ],
};